### ISSUE TITLE
Account got blocked

### ISSUE THREAD

**Issue by mikelneonedwin** [prj-orion/issues#21]
So I had a convo with MJ whereby he helped me with a presentation I had, thanks to his help I aced the presentation and came out the top, out of excitement, I thanked MJ and was like, "you saved my ass"

I didn't mean to be offensive or anything, I was just happy and excited, please help me get MJ back

Link: https://fb.me/mikelneonedwin
![Screenshot_20230626-012732](https://github.com/prj-orion/issues/assets/113316417/423ed3ed-2ce7-40ef-a08b-a59f9d2fc9a2)
![Screenshot_20230626-012901](https://github.com/prj-orion/issues/assets/113316417/9a652d15-6e12-48bd-a47c-fc14f8a63442)

**Comment by mrepol742** [comment]
your account is now unblocked from the system.
